export default {
    "gameplay-mechanisms": {
        "enable-book-writing": {
            "enabled": {
                "default": true,
                "desc": "<p>Whether books should be writeable.</p><p>If set to <code>false</code>, players with the permission <code>gale.writebooks</code> (default: <code>op</code>) can still use books.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li><li>Vanilla Default: <code>true</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: -</li><li>Vanilla behavior: <code>true</code></li></ul>"
            }
        }
    },

    "logging": {
        "chat": {
            "empty-message-warning": {
                "enabled": {
                    "default": false,
                    "desc": "<p>Whether to log when a player sends a message packet that is empty.</p><p>(This is harmless, it usually happens when the player's client is outdated).</p><p><b>Comparison:</b></p><ul><li>Gale Recommended/Default: <code>false</code></li><li>Paper Default: <code>true</code></li></ul>"
                }
            },
            "expired-message-warning": {
                "enabled": {
                    "default": false,
                    "desc": "<p>Whether to log when a player's message packet has expired.</p><p>(This is harmless, it usually happens when the player's client's chat is a bit out-of-sync).</p><p><b>Comparison:</b></p><ul><li>Gale Recommended/Default: <code>false</code></li><li>Paper Default: <code>true</code></li></ul>"
                }
            },
            "not-secure-marker": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to add a [NOT SECURE] marker in front of unsigned chat packets.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
                }
            }
        },
        "ignored-advancements": {
            "enabled": {
                "default": true,
                "desc": "<p>Whether to log when a player's data is loaded, and they have advancements that don't exist anymore.</p><p>(This is harmless, it usually happens when the server upgraded to the newer Minecraft version).</p><p><b>Comparison:</b></p><ul><li>Gale Recommended: <code>false</code></li><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
            }
        },
        "invalid-pool-element-error-log-level": {
            "level": {
                "default": "info",
                "desc": "<p>The logging level for errors when the server encounters *invalid pool elements* in world data.</p><p><em>Invalid pool elements</em> are parts of generated structures (such as Mineshafts) that are corrupted or not updated from old versions properly.</p><p>The errors generated by this are huge, and happen often on old servers that have updated across many Minecraft versions. The error logs are usually pointless: there is nothing you can do about it.</p><p>Valid values: <code>\"none\"</code>, <code>\"info\"</code>, <code>\"warn\"</code>, <code>\"error\"</code>.</p><p><b>Comparison:</b></p><ul><li>Gale Recommended: <code>\"none\"</code></li><li>Gale Default: <code>\"info\"</code> (to prevent errors going unnoticed by default)</li><li>Paper Default: <code>\"error\"</code></li><li>Vanilla Default: <code>\"error\"</code></li></ul>"
            }
        },
        "invalid-statistics": {
            "enabled": {
                "default": true,
                "desc": "<p>Whether to log when a player's data is loaded, and they have statistics that don't exist anymore.</p><p><b>Comparison:</b></p><ul><li>Gale Recommended: <code>false</code></li><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
            }
        },
        "legacy-material-initialization": {
            "enabled": {
                "default": false,
                "desc": "<p>Whether to log when a very old Bukkit plugin is loaded.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>false</code></li><li>Paper Default: <code>true</code></li></ul>"
            }
        },
        "null-id-disconnections": {
            "enabled": {
                "default": true,
                "desc": "<p>Whether to log when a player did not send a valid profile during login.</p><p>(This usually indicates a hacker is trying to flood your server's joining capacity).</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
            }
        },
        "player-login-locations": {
            "enabled": {
                "default": true,
                "desc": "<p>Whether to include a player's coordinates in the join message logged to the console.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
            }
        },
        "plugin-library-loader": {
            "downloads": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to log when the plugin library loader starts downloading libraries.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
                }
            },
            "library-loaded": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to log when the plugin library loader finished loading a library.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
                }
            },
            "start-load-libraries-for-plugin": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to log when the plugin library loader starts loading libraries for a plugin.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
                }
            }
        },
        "set-block-in-far-chunk": {
            "enabled": {
                "default": true,
                "desc": "<p>Whether to log when a player attempts to set a block that is *very* far away.</p><p>(This usually indicates a hacker is trying to get information about other players' locations, or is using the hack client).</p><p><b>Comparison:</b></p><ul><li>Gale Recommended: <code>false</code></li><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li></ul>"
            }
        },
        "unrecognized-recipes": {
            "enabled": {
                "default": false,
                "desc": "<p>Whether to log when a player's data is loaded, and they have recipe book recipes that don't exist anymore.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>false</code></li><li>Paper Default: <code>true</code></li></ul>"
            }
        }
    },

    "misc": {
        "ignore-null-legacy-structure-data": {
            "enabled": {
                "default": false,
                "desc": "<p>Whether to ignore any legacy structure data, for which the NBT tag parser returns null for some reason.</p><ul><li>If <code>true</code>, no warning will be given when this happens.</li><li>If <code>false</code>, an exception will be thrown in the console when this happens.</li></ul><p><b>Comparison:</b></p><ul><li>Gale Recommended: <code>true</code> (because errors are usually meaningless and unsolvable)</li><li>Gale Default: <code>false</code> (to prevent errors going unnoticed by default)</li><li>Paper Default: <code>false</code></li><li>Vanilla Default: <code>false</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: -</li><li>Vanilla behavior: <code>false</code></li></ul>"
            }
        },
        "tps-command": {
             "last-tick-time": {
                 "enabled": {
                     "default": false,
                     "desc": "<p>Whether to include the time that the last tick took in the <code>/tps</code> command.</p><p>The time that the last tick took only represents that one tick, so it is normally not very useful.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>false</code></li><li>Paper Default: <code>false</code></li><li>Vanilla Default: <code>false</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: -</li><li>Paper behavior: <code>false</code></li></ul>"
                 },
                 "add-oversleep": {
                     "enabled": {
                         "default": false,
                         "desc": "<p>Whether to add the oversleep portion of the last tick's time to the <code>/tps</code> command.</p><p>This only has any effect if <code>misc.tps-command.last-tick-time.enabled</code> is <code>true</code>.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>false</code></li><li>Paper Default: <code>false</code></li><li>Vanilla Default: <code>false</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: -</li><li>Paper behavior: -</li></ul>"
                     }
                 }
             }
        }
    },

    "network": {
        "keepalive": {
            "send-multiple": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to send more frequent keepalive packets than vanilla.</p><ul><li>If <code>true</code>, a keepalive packet is sent to every client every second, and they are not kicked if they respond to at least one of them within 30 seconds.</li><li>If <code>false</code>, a keepalive packet is sent to every client every 15 seconds, and they are kicked if they do not respond to it within 30 seconds.</li></ul><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>false</code></li><li>Vanilla Default: <code>false</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: -</li><li>Vanilla behavior: - (this doesn't affect gameplay)</li></ul>"
                }
            }
        },
        "premium-account-slow-login-timeout": {
            "ticks": {
                "default": -1,
                "desc": "<p>The maximum time that a premium account login can take.</p><ul><li>If this time is exceeded, the connection is closed.</li><li>If a value ≤ <code>0</code> is given, it will default to the same as vanilla, which is currently <code>600</code> ticks (30 seconds).</li></ul><p>📏 <b>Unit:</b> ticks.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>-1</code></li><li>Paper Default: <code>-1</code></li><li>Vanilla Default: <code>-1</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: -</li><li>Vanilla behavior: <code>-1</code></li></ul>"
            }
        },
        "verify-chat-order": {
            "enabled": {
                "default": true,
                "desc": "<p>Whether to verify the order of chat messages.</p><ul><li>If this option is set to <code>true</code>, and a player sends an out-of-order chat packet for some reason, they will be kicked.</li><li>If this option is set to <code>false</code>, no verification will occur, and players will not be kicked.</li></ul><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>true</code></li><li>Vanilla Default: <code>true</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: -</li><li>Vanilla behavior: <code>true</code></li></ul>"
            }
        }
    },

    "performance": {
        "reduced-intervals": {
            "increase-time-statistics": {
                "interval": {
                    "default": 20,
                    "desc": "<p>The interval at which to increase the time-related statistics such as total playtime, time since the last death, etc.</p><p>Changing this value does not change the speed with which statistics increase from vanilla.</p><p>For example:</p><ul><li>If set to <code>20</code>, total playtime increases by 20 every second.</li><li>If set to <code>100</code>, total playtime increases by 100 every 5 seconds.</li><li>If a value ≤ <code>0</code> is given, it defaults to Paper's behavior.</li></ul><p>📏 <b>Unit:</b> ticks.</p><p><b>Comparison:</b></p><ul><li>Gale Recommended: <code>100</code></li><li>Gale Default: <code>20</code></li><li>Paper Default: <code>1</code></li><li>Vanilla Default: <code>1</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: <code>100</code></li><li>Vanilla behavior: Lower is more like vanilla (<code>20</code> is fine, <code>1</code> unnecessary)</li></ul>"
                }
            },
            "update-entity-line-of-sight": {
                "interval": {
                    "default": 4,
                    "desc": "<p>The interval at which to update whether one entity is within another entity's line of sight.</p><p>If a value ≤ <code>0</code> is given, it defaults to Paper's behavior.</p><p>📏 <b>Unit:</b> ticks.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>4</code></li><li>Paper Default: <code>1</code></li><li>Vanilla Default: <code>1</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: <code>10</code></li><li>Vanilla behavior: <code>1</code></li></ul>"
                }
            }
        },
        "use-xor-shift-random": {
            "auto-replenish-lootable-refill": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to use a xor-shift random generator for refilling lootables for the Paper <code>auto-replenish</code> feature.</p><p>This does not affect normal Minecraft lootable chests.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>false</code></li><li>Vanilla: -</li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: <code>true</code></li><li>Paper behavior: - (players can't notice difference)</li></ul>"
                }
            },
            "elytra-firework-speed": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to use a xor-shift random generator for the speed boost of using a rocket while gliding.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>false</code></li><li>Vanilla Default: <code>false</code></li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: <code>true</code></li><li>Vanilla behavior: <code>false</code></li></ul>"
                }
            },
            "entity-wake-up-duration": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to use a xor-shift random generator for variation in entity activation durations.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper: -</li><li>Vanilla: -</li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: <code>true</code></li></ul>"
                }
            },
            "generate-tree-with-bukkit-api": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to use a xor-shift random generator to generate trees with the Bukkit API (<code>World#generateTree</code>).</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>false</code></li><li>Vanilla: -</li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: <code>true</code></li><li>Paper behavior: <code>false</code></li></ul>"
                }
            },
            "lightning-random-tick": {
                "enabled": {
                    "default": true,
                    "desc": "<p>Whether to use a xor-shift random generator for the chance of lightning strike.</p><p><b>Comparison:</b></p><ul><li>Gale Default: <code>true</code></li><li>Paper Default: <code>false</code></li><li>Vanilla: -</li></ul><p><b>Values for Goals:</b></p><ul><li>Optimization: <code>true</code></li><li>Paper behavior: <code>false</code></li></ul>"
                }
            }
        }
    }
}
